/**
 * 逆引きホスト名に埋め込まれた地名コードから位置を推定する。
 * バックボーン事業者はルータ名に CLLI (例: sttlwa = Seattle, WA) や IATA
 * (例: lax) を入れる慣習があり、IP ジオロケーション DB より信頼できることが多い。
 * ここでは主要ハブだけを持つ小さな表で、確信の持てるトークンだけを拾う。
 */

import type { GeoCandidate } from "./types";

interface Place {
  city: string;
  country: string;
  cc: string;
  lat: number;
  lon: number;
}

const P = (city: string, country: string, cc: string, lat: number, lon: number): Place => ({
  city,
  country,
  cc,
  lat,
  lon,
});

// --- 都市定義 (座標は市街中心の概略) ---
const CITY = {
  seattle: P("Seattle", "United States", "US", 47.61, -122.33),
  portland: P("Portland", "United States", "US", 45.52, -122.68),
  sanjose: P("San Jose", "United States", "US", 37.34, -121.89),
  paloalto: P("Palo Alto", "United States", "US", 37.44, -122.14),
  sanfrancisco: P("San Francisco", "United States", "US", 37.77, -122.42),
  sacramento: P("Sacramento", "United States", "US", 38.58, -121.49),
  losangeles: P("Los Angeles", "United States", "US", 34.05, -118.24),
  sandiego: P("San Diego", "United States", "US", 32.72, -117.16),
  lasvegas: P("Las Vegas", "United States", "US", 36.17, -115.14),
  phoenix: P("Phoenix", "United States", "US", 33.45, -112.07),
  saltlake: P("Salt Lake City", "United States", "US", 40.76, -111.89),
  denver: P("Denver", "United States", "US", 39.74, -104.99),
  dallas: P("Dallas", "United States", "US", 32.78, -96.8),
  houston: P("Houston", "United States", "US", 29.76, -95.37),
  austin: P("Austin", "United States", "US", 30.27, -97.74),
  sanantonio: P("San Antonio", "United States", "US", 29.42, -98.49),
  kansascity: P("Kansas City", "United States", "US", 39.1, -94.58),
  stlouis: P("St. Louis", "United States", "US", 38.63, -90.2),
  minneapolis: P("Minneapolis", "United States", "US", 44.98, -93.27),
  chicago: P("Chicago", "United States", "US", 41.88, -87.63),
  detroit: P("Detroit", "United States", "US", 42.33, -83.05),
  cleveland: P("Cleveland", "United States", "US", 41.5, -81.69),
  columbus: P("Columbus", "United States", "US", 39.96, -83.0),
  atlanta: P("Atlanta", "United States", "US", 33.75, -84.39),
  miami: P("Miami", "United States", "US", 25.76, -80.19),
  tampa: P("Tampa", "United States", "US", 27.95, -82.46),
  orlando: P("Orlando", "United States", "US", 28.54, -81.38),
  charlotte: P("Charlotte", "United States", "US", 35.23, -80.84),
  raleigh: P("Raleigh", "United States", "US", 35.78, -78.64),
  ashburn: P("Ashburn", "United States", "US", 39.04, -77.49),
  washington: P("Washington, D.C.", "United States", "US", 38.9, -77.04),
  baltimore: P("Baltimore", "United States", "US", 39.29, -76.61),
  philadelphia: P("Philadelphia", "United States", "US", 39.95, -75.17),
  pittsburgh: P("Pittsburgh", "United States", "US", 40.44, -80.0),
  newyork: P("New York", "United States", "US", 40.71, -74.01),
  newark: P("Newark", "United States", "US", 40.74, -74.17),
  boston: P("Boston", "United States", "US", 42.36, -71.06),
  honolulu: P("Honolulu", "United States", "US", 21.31, -157.86),
  montreal: P("Montreal", "Canada", "CA", 45.5, -73.57),
  toronto: P("Toronto", "Canada", "CA", 43.65, -79.38),
  vancouver: P("Vancouver", "Canada", "CA", 49.28, -123.12),
  calgary: P("Calgary", "Canada", "CA", 51.05, -114.07),
  mexicocity: P("Mexico City", "Mexico", "MX", 19.43, -99.13),
  saopaulo: P("São Paulo", "Brazil", "BR", -23.55, -46.63),
  rio: P("Rio de Janeiro", "Brazil", "BR", -22.91, -43.17),
  buenosaires: P("Buenos Aires", "Argentina", "AR", -34.6, -58.38),
  santiago: P("Santiago", "Chile", "CL", -33.45, -70.67),
  bogota: P("Bogotá", "Colombia", "CO", 4.71, -74.07),
  tokyo: P("Tokyo", "Japan", "JP", 35.68, 139.77),
  osaka: P("Osaka", "Japan", "JP", 34.69, 135.5),
  nagoya: P("Nagoya", "Japan", "JP", 35.18, 136.91),
  fukuoka: P("Fukuoka", "Japan", "JP", 33.59, 130.4),
  sapporo: P("Sapporo", "Japan", "JP", 43.06, 141.35),
  seoul: P("Seoul", "South Korea", "KR", 37.57, 126.98),
  busan: P("Busan", "South Korea", "KR", 35.18, 129.08),
  taipei: P("Taipei", "Taiwan", "TW", 25.03, 121.57),
  hongkong: P("Hong Kong", "Hong Kong", "HK", 22.32, 114.17),
  shanghai: P("Shanghai", "China", "CN", 31.23, 121.47),
  beijing: P("Beijing", "China", "CN", 39.9, 116.4),
  singapore: P("Singapore", "Singapore", "SG", 1.35, 103.82),
  kualalumpur: P("Kuala Lumpur", "Malaysia", "MY", 3.14, 101.69),
  jakarta: P("Jakarta", "Indonesia", "ID", -6.21, 106.85),
  bangkok: P("Bangkok", "Thailand", "TH", 13.76, 100.5),
  manila: P("Manila", "Philippines", "PH", 14.6, 120.98),
  hanoi: P("Hanoi", "Vietnam", "VN", 21.03, 105.85),
  mumbai: P("Mumbai", "India", "IN", 19.08, 72.88),
  delhi: P("Delhi", "India", "IN", 28.61, 77.21),
  chennai: P("Chennai", "India", "IN", 13.08, 80.27),
  sydney: P("Sydney", "Australia", "AU", -33.87, 151.21),
  melbourne: P("Melbourne", "Australia", "AU", -37.81, 144.96),
  perth: P("Perth", "Australia", "AU", -31.95, 115.86),
  brisbane: P("Brisbane", "Australia", "AU", -27.47, 153.03),
  auckland: P("Auckland", "New Zealand", "NZ", -36.85, 174.76),
  london: P("London", "United Kingdom", "GB", 51.51, -0.13),
  manchester: P("Manchester", "United Kingdom", "GB", 53.48, -2.24),
  dublin: P("Dublin", "Ireland", "IE", 53.35, -6.26),
  amsterdam: P("Amsterdam", "Netherlands", "NL", 52.37, 4.9),
  brussels: P("Brussels", "Belgium", "BE", 50.85, 4.35),
  paris: P("Paris", "France", "FR", 48.86, 2.35),
  marseille: P("Marseille", "France", "FR", 43.3, 5.37),
  frankfurt: P("Frankfurt", "Germany", "DE", 50.11, 8.68),
  hamburg: P("Hamburg", "Germany", "DE", 53.55, 9.99),
  berlin: P("Berlin", "Germany", "DE", 52.52, 13.41),
  munich: P("Munich", "Germany", "DE", 48.14, 11.58),
  dusseldorf: P("Düsseldorf", "Germany", "DE", 51.23, 6.78),
  zurich: P("Zurich", "Switzerland", "CH", 47.38, 8.54),
  geneva: P("Geneva", "Switzerland", "CH", 46.2, 6.14),
  vienna: P("Vienna", "Austria", "AT", 48.21, 16.37),
  prague: P("Prague", "Czechia", "CZ", 50.08, 14.44),
  warsaw: P("Warsaw", "Poland", "PL", 52.23, 21.01),
  milan: P("Milan", "Italy", "IT", 45.46, 9.19),
  rome: P("Rome", "Italy", "IT", 41.9, 12.5),
  madrid: P("Madrid", "Spain", "ES", 40.42, -3.7),
  barcelona: P("Barcelona", "Spain", "ES", 41.39, 2.17),
  lisbon: P("Lisbon", "Portugal", "PT", 38.72, -9.14),
  copenhagen: P("Copenhagen", "Denmark", "DK", 55.68, 12.57),
  stockholm: P("Stockholm", "Sweden", "SE", 59.33, 18.07),
  oslo: P("Oslo", "Norway", "NO", 59.91, 10.75),
  helsinki: P("Helsinki", "Finland", "FI", 60.17, 24.94),
  athens: P("Athens", "Greece", "GR", 37.98, 23.73),
  istanbul: P("Istanbul", "Turkey", "TR", 41.01, 28.98),
  moscow: P("Moscow", "Russia", "RU", 55.76, 37.62),
  dubai: P("Dubai", "United Arab Emirates", "AE", 25.2, 55.27),
  telaviv: P("Tel Aviv", "Israel", "IL", 32.08, 34.78),
  cairo: P("Cairo", "Egypt", "EG", 30.04, 31.24),
  johannesburg: P("Johannesburg", "South Africa", "ZA", -26.2, 28.05),
  capetown: P("Cape Town", "South Africa", "ZA", -33.93, 18.42),
  nairobi: P("Nairobi", "Kenya", "KE", -1.29, 36.82),
  lagos: P("Lagos", "Nigeria", "NG", 6.52, 3.38),
} as const;

/** IATA 空港コードなど 3 文字トークン (単独トークンとして現れた場合のみ) */
const IATA: Record<string, Place> = {
  sea: CITY.seattle,
  pdx: CITY.portland,
  sjc: CITY.sanjose,
  pao: CITY.paloalto,
  sfo: CITY.sanfrancisco,
  smf: CITY.sacramento,
  lax: CITY.losangeles,
  san: CITY.sandiego,
  las: CITY.lasvegas,
  phx: CITY.phoenix,
  slc: CITY.saltlake,
  den: CITY.denver,
  dfw: CITY.dallas,
  dal: CITY.dallas,
  iah: CITY.houston,
  hou: CITY.houston,
  aus: CITY.austin,
  sat: CITY.sanantonio,
  mci: CITY.kansascity,
  stl: CITY.stlouis,
  msp: CITY.minneapolis,
  ord: CITY.chicago,
  chi: CITY.chicago,
  dtw: CITY.detroit,
  cle: CITY.cleveland,
  cmh: CITY.columbus,
  atl: CITY.atlanta,
  mia: CITY.miami,
  tpa: CITY.tampa,
  mco: CITY.orlando,
  clt: CITY.charlotte,
  rdu: CITY.raleigh,
  iad: CITY.ashburn,
  ash: CITY.ashburn,
  dca: CITY.washington,
  was: CITY.washington,
  bwi: CITY.baltimore,
  phl: CITY.philadelphia,
  pit: CITY.pittsburgh,
  jfk: CITY.newyork,
  nyc: CITY.newyork,
  lga: CITY.newyork,
  ewr: CITY.newark,
  bos: CITY.boston,
  hnl: CITY.honolulu,
  yul: CITY.montreal,
  yyz: CITY.toronto,
  tor: CITY.toronto,
  yvr: CITY.vancouver,
  yyc: CITY.calgary,
  mex: CITY.mexicocity,
  gru: CITY.saopaulo,
  sao: CITY.saopaulo,
  gig: CITY.rio,
  rio: CITY.rio,
  eze: CITY.buenosaires,
  bue: CITY.buenosaires,
  scl: CITY.santiago,
  bog: CITY.bogota,
  tyo: CITY.tokyo,
  nrt: CITY.tokyo,
  hnd: CITY.tokyo,
  tky: CITY.tokyo,
  osa: CITY.osaka,
  kix: CITY.osaka,
  itm: CITY.osaka,
  ngo: CITY.nagoya,
  fuk: CITY.fukuoka,
  cts: CITY.sapporo,
  sel: CITY.seoul,
  icn: CITY.seoul,
  pus: CITY.busan,
  tpe: CITY.taipei,
  hkg: CITY.hongkong,
  pvg: CITY.shanghai,
  sha: CITY.shanghai,
  pek: CITY.beijing,
  bjs: CITY.beijing,
  sin: CITY.singapore,
  kul: CITY.kualalumpur,
  cgk: CITY.jakarta,
  jkt: CITY.jakarta,
  bkk: CITY.bangkok,
  mnl: CITY.manila,
  han: CITY.hanoi,
  bom: CITY.mumbai,
  del: CITY.delhi,
  maa: CITY.chennai,
  syd: CITY.sydney,
  mel: CITY.melbourne,
  per: CITY.perth,
  bne: CITY.brisbane,
  akl: CITY.auckland,
  lhr: CITY.london,
  lon: CITY.london,
  ldn: CITY.london,
  man: CITY.manchester,
  dub: CITY.dublin,
  ams: CITY.amsterdam,
  bru: CITY.brussels,
  cdg: CITY.paris,
  par: CITY.paris,
  mrs: CITY.marseille,
  fra: CITY.frankfurt,
  ham: CITY.hamburg,
  ber: CITY.berlin,
  muc: CITY.munich,
  dus: CITY.dusseldorf,
  zrh: CITY.zurich,
  gva: CITY.geneva,
  vie: CITY.vienna,
  prg: CITY.prague,
  waw: CITY.warsaw,
  mxp: CITY.milan,
  mil: CITY.milan,
  fco: CITY.rome,
  rom: CITY.rome,
  mad: CITY.madrid,
  bcn: CITY.barcelona,
  lis: CITY.lisbon,
  cph: CITY.copenhagen,
  arn: CITY.stockholm,
  sto: CITY.stockholm,
  osl: CITY.oslo,
  hel: CITY.helsinki,
  ath: CITY.athens,
  ist: CITY.istanbul,
  mow: CITY.moscow,
  dxb: CITY.dubai,
  tlv: CITY.telaviv,
  cai: CITY.cairo,
  jnb: CITY.johannesburg,
  cpt: CITY.capetown,
  nbo: CITY.nairobi,
  los: CITY.lagos,
};

/** CLLI 風の 6 文字地名コード (NTT gin.ntt.net など北米系事業者の慣習) */
const CLLI: Record<string, Place> = {
  sttlwa: CITY.seattle,
  ptldor: CITY.portland,
  snjsca: CITY.sanjose,
  plalca: CITY.paloalto,
  snfcca: CITY.sanfrancisco,
  sacrca: CITY.sacramento,
  lsanca: CITY.losangeles,
  sndgca: CITY.sandiego,
  lsvgnv: CITY.lasvegas,
  phnxaz: CITY.phoenix,
  slkcut: CITY.saltlake,
  dnvrco: CITY.denver,
  dllstx: CITY.dallas,
  hstntx: CITY.houston,
  austtx: CITY.austin,
  snantx: CITY.sanantonio,
  kscymo: CITY.kansascity,
  stlsmo: CITY.stlouis,
  mplsmn: CITY.minneapolis,
  chcgil: CITY.chicago,
  dtrtmi: CITY.detroit,
  clevoh: CITY.cleveland,
  clmboh: CITY.columbus,
  atlnga: CITY.atlanta,
  miamfl: CITY.miami,
  tampfl: CITY.tampa,
  orldfl: CITY.orlando,
  chrlnc: CITY.charlotte,
  rlghnc: CITY.raleigh,
  asbnva: CITY.ashburn,
  washdc: CITY.washington,
  bltmmd: CITY.baltimore,
  phlapa: CITY.philadelphia,
  pitbpa: CITY.pittsburgh,
  nycmny: CITY.newyork,
  nwrknj: CITY.newark,
  bstnma: CITY.boston,
  hnlhhi: CITY.honolulu,
  mtrlpq: CITY.montreal,
  toroon: CITY.toronto,
  vancbc: CITY.vancouver,
  tokyjp: CITY.tokyo,
  osakjp: CITY.osaka,
  sngpsi: CITY.singapore,
  hkghhk: CITY.hongkong,
  sydnau: CITY.sydney,
  londen: CITY.london,
  frnkge: CITY.frankfurt,
  amstnl: CITY.amsterdam,
  parsfr: CITY.paris,
  madrsp: CITY.madrid,
  milnit: CITY.milan,
  brusbe: CITY.brussels,
  dsdfge: CITY.dusseldorf,
  stkhsw: CITY.stockholm,
  cpnhdk: CITY.copenhagen,
};

/** 事業者固有の略号 (IATA と衝突するものはドメインで限定) */
const OPERATOR_ALIASES: Array<{ domain: RegExp; tokens: Record<string, Place> }> = [
  {
    // Arelion (旧 Telia Carrier): xxx-bb#-link.ip.twelve99.net
    domain: /(^|\.)twelve99\.net$/,
    tokens: {
      sjo: CITY.sanjose,
      palo: CITY.paloalto,
      kanc: CITY.kansascity,
      nyk: CITY.newyork,
      ldn: CITY.london,
      hbg: CITY.hamburg,
      ffm: CITY.frankfurt,
      adm: CITY.amsterdam,
      prs: CITY.paris,
      cph: CITY.copenhagen,
      sto: CITY.stockholm,
      hls: CITY.helsinki,
      osl: CITY.oslo,
      tky: CITY.tokyo,
      snge: CITY.singapore,
      hnk: CITY.hongkong,
    },
  },
];

export function hostnameLocation(hostname: string | null | undefined): GeoCandidate | null {
  if (!hostname) return null;
  const host = hostname.toLowerCase();
  const tokens = host.split(/[.\-_]/).filter(Boolean);
  let place: Place | null = null;

  for (const alias of OPERATOR_ALIASES) {
    if (!alias.domain.test(host)) continue;
    for (const t of tokens) {
      const p = alias.tokens[t];
      if (p) {
        place = p;
        break;
      }
    }
    if (place) break;
  }
  if (!place) {
    for (const t of tokens) {
      // CLLI 風: 英字6文字 + 任意の数字 (sttlwa01)
      const m = t.match(/^([a-z]{6})\d{0,3}$/);
      if (m && CLLI[m[1]]) {
        place = CLLI[m[1]];
        break;
      }
    }
  }
  if (!place) {
    for (const t of tokens) {
      if (t.length === 3 && IATA[t]) {
        place = IATA[t];
        break;
      }
    }
  }
  if (!place) return null;
  return {
    source: "hostname",
    lat: place.lat,
    lon: place.lon,
    city: place.city,
    country: place.country,
    countryCode: place.cc,
  };
}
